/**
 * Unified built-in source registry.
 * Single source of truth for both constellation provenance and search sources.
 * Matches the shape of rows from the source_registry DB table.
 * Used as offline/initial fallback when the DB fetch hasn't completed.
 */

export const BUILTIN_SOURCES = [
  // --- Provenance sources (constellation labels) ---
  {
    id: 'elder',
    name: 'Elder-verified',
    short_name: 'Elder',
    description: 'Verified by language elders',
    source_type: 'provenance',
    icon: null,
    symbol: '\u25C6', // ◆
    core_color: '#FFD700',
    scale: 1.0,
    opacity: 1.0,
    glow: true,
    adapter_id: null,
    adapter_config: {},
    supported_languages: null,
    is_builtin: true,
    enabled_by_default: true,
    is_searchable: false,
    is_importable: false,
    display_order: 10,
  },
  {
    id: 'community',
    name: 'Community-contributed',
    short_name: 'Community',
    description: 'Contributed by community members',
    source_type: 'provenance',
    icon: null,
    symbol: '\u25C7', // ◇
    core_color: '#00D4FF',
    scale: 0.9,
    opacity: 0.85,
    glow: true,
    adapter_id: null,
    adapter_config: {},
    supported_languages: null,
    is_builtin: true,
    enabled_by_default: true,
    is_searchable: false,
    is_importable: false,
    display_order: 20,
  },
  {
    id: 'dictionary',
    name: 'Published dictionary',
    short_name: 'Dictionary',
    description: 'From published dictionaries',
    source_type: 'provenance',
    icon: null,
    symbol: '\u25CF', // ●
    core_color: '#7BA3E0',
    scale: 0.8,
    opacity: 0.7,
    glow: false,
    adapter_id: null,
    adapter_config: {},
    supported_languages: null,
    is_builtin: true,
    enabled_by_default: true,
    is_searchable: false,
    is_importable: false,
    display_order: 30,
  },
  {
    id: 'academic',
    name: 'Academic/linguistic',
    short_name: 'Academic',
    description: 'Academic and linguistic research',
    source_type: 'provenance',
    icon: null,
    symbol: '\u25A0', // ■
    core_color: '#90CAF9',
    scale: 0.7,
    opacity: 0.65,
    glow: false,
    adapter_id: null,
    adapter_config: {},
    supported_languages: null,
    is_builtin: true,
    enabled_by_default: true,
    is_searchable: false,
    is_importable: false,
    display_order: 40,
  },
  {
    id: 'ai',
    name: 'AI-suggested',
    short_name: 'AI',
    description: 'Suggested by AI models',
    source_type: 'provenance',
    icon: null,
    symbol: '\u25CB', // ○
    core_color: '#9B7FD4',
    scale: 0.6,
    opacity: 0.35,
    glow: false,
    adapter_id: null,
    adapter_config: {},
    supported_languages: null,
    is_builtin: true,
    enabled_by_default: true,
    is_searchable: false,
    is_importable: false,
    display_order: 50,
  },

  // --- Search sources ---
  {
    id: 'personal',
    name: 'My Decks',
    short_name: 'Mine',
    description: 'Search your personal decks',
    source_type: 'search',
    icon: 'BookOpen',
    symbol: '\u25CF',
    core_color: '#10b981',
    scale: 0.8,
    opacity: 0.7,
    glow: false,
    adapter_id: 'personal',
    adapter_config: {},
    supported_languages: null,
    is_builtin: true,
    enabled_by_default: true,
    is_searchable: true,
    is_importable: false,
    display_order: 60,
  },
  {
    id: 'community_search',
    name: 'Community',
    short_name: 'Community',
    description: 'Search community decks',
    source_type: 'search',
    icon: 'Users',
    symbol: '\u25CF',
    core_color: '#6366f1',
    scale: 0.8,
    opacity: 0.7,
    glow: false,
    adapter_id: 'community',
    adapter_config: {},
    supported_languages: null,
    is_builtin: true,
    enabled_by_default: true,
    is_searchable: true,
    is_importable: false,
    display_order: 70,
  },
  {
    id: 'freeDictionary',
    name: 'Free Dictionary',
    short_name: 'Free Dict',
    description: 'English-only dictionary API',
    source_type: 'search',
    icon: 'BookMarked',
    symbol: '\u25CF',
    core_color: '#f59e0b',
    scale: 0.8,
    opacity: 0.7,
    glow: false,
    adapter_id: 'freeDictionary',
    adapter_config: {},
    supported_languages: ['en'],
    is_builtin: true,
    enabled_by_default: true,
    is_searchable: true,
    is_importable: false,
    display_order: 80,
  },
  {
    id: 'wiktionary',
    name: 'Wiktionary',
    short_name: 'Wiktionary',
    description: 'Multilingual wiki dictionary',
    source_type: 'search',
    icon: 'Globe',
    symbol: '\u25CF',
    core_color: '#8b5cf6',
    scale: 0.8,
    opacity: 0.7,
    glow: false,
    adapter_id: 'wiktionary',
    adapter_config: {},
    supported_languages: null,
    is_builtin: true,
    enabled_by_default: true,
    is_searchable: true,
    is_importable: true,
    display_order: 90,
  },
];

/** Map from source id to source object for O(1) lookup */
export const BUILTIN_SOURCE_MAP = new Map(
  BUILTIN_SOURCES.map(s => [s.id, s])
);

/** All search source IDs */
export const BUILTIN_SEARCH_IDS = BUILTIN_SOURCES
  .filter(s => s.is_searchable)
  .map(s => s.id);

/** Default-enabled search source IDs (for appStore initial state) */
export const DEFAULT_ENABLED_SEARCH = BUILTIN_SOURCES
  .filter(s => s.is_searchable && s.enabled_by_default)
  .map(s => s.id);
